Added Examples task and nursing handoff
Nictiz/Nictiz-STU3-eOverdracht pull request #3
Opened 2021-09-30 07:51 UTC by mikdejong

2021-10-01 14:25 UTC, pieter-edelman-nictiz requested changes
Although we should re-use the examples from the zib project for the actual content of all zib profiles, I think it makes sense to create an example patient and example hospital and home care organization, plus their associated healthcare providers, as this demonstrates the use case better (transfer of care between different organizations).

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +    <implicitRules value="http://hl7.org/fhir/reference" />
This is something that we don't normally include and it's kind of dangerous as it is labeled as `isModifier`. I'd suggest you remove it.

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +    <statusReason>
"abc" is not really useful. You can actually use this field to elaborate on the particular use case (so something along the lines of "The use case here is to transfer the patient without negotiation, so status is set to _accepted_ directly")

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +        <display value="Test patientje" />
This display doesn't align to the content

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +            <display value="Test zorgverlener" />
This display doesn't align to the content

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +            <display value="Test zorgverlener" />
Please also use the PractitionerRole extension here (see the profile).

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +        <display value="Test organisatie" />
This display doesn't align with the content.

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +            <display value="Test gegevens" />
This isn't a very useful display

2021-10-01 14:25 UTC, pieter-edelman-nictiz commented on Examples/eOverdracht-NursingHandoff-Adults.xml
> +<?xml version="1.0" encoding="utf-8"?>
This is the profile, not the instance ...

2021-10-05 07:27 UTC, pieter-edelman-nictiz requested changes
Ziet er goed uit Mik! Nog een paar dingetjes, vooral dat de gekozen resources niet goed aansluiten bij het voorbeeld dat je hier probeert te demonstreren. Maar dat is ook vooral een kwestie van de juiste voorbeeld-resources voor zender en ontvanger maken.

2021-10-05 07:27 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> -        <profile value="http://nictiz.nl/fhir/StructureDefinition/eOverdracht-Task" />
`.meta.profile` moet nou juist wél blijven staan.

2021-10-05 07:27 UTC, pieter-edelman-nictiz commented on Examples/Task-01.xml
> +            <extension url="http://nictiz.nl/fhir/StructureDefinition/practitionerrole-reference">
Dit komt misschien niet helemaal overeen met de use case die we hier proberen te demonstreren (VVT stuurt patiënt naar het ziekenhuis). Maar goed, we wilden nog eigen zorgverleners voor dit project definiëren, dus dat komt dan nog wel.

2021-10-05 07:27 UTC, pieter-edelman-nictiz commented on Examples/eOverdracht-NursingHandoff-Adults.xml
> +    <id value="nursing-handoff-01" />
We hebben [ergens opgeschreven](https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_STU3#Examples_and_fixtures) dat we id's en bestandsnamen gelijktrekken en bovendien op een bepaalde manier vormgeven ([profiel-id]-[unieke string]). Dus graag bestandsnaam en `.id` aanpassen naar "eOverdracht-NursingHandoff-Adults-01".

2021-10-05 07:27 UTC, pieter-edelman-nictiz commented on Examples/eOverdracht-NursingHandoff-Adults.xml
> +            <entry>
Even goed kijken wat PractitionerRole behelst: dit vertelt je welke rol een zorgverlener speelt voor een organisatie. De PractitionerRole moet dus overeen komen met de Organisation en de Practitioner die hier vermeld staan.

2021-10-05 07:27 UTC, pieter-edelman-nictiz commented on Examples/eOverdracht-NursingHandoff-Adults.xml
> +            <entry>
Deze drie resources komen niet overeen met het voorbeeld van een patiënt die met spoed vanuit de VVT wordt opgenomen in het ziekenhuis. Waarschijnlijk wil je hier niet eens een zorgverlener definiëren (maar misschien wel een PractitionerRole om bv. aan te geven dat de patiënt naar een cardioloog in het ziekenhuis moet).

2021-10-05 07:27 UTC, pieter-edelman-nictiz commented on Examples/eOverdracht-NursingHandoff-Adults.xml
> +                <reference value="Encounter/eOverdracht-encounter-01" />
Deze instance moet nog gemaakt worden, toch?

2021-10-05 08:06 UTC, mikdejong commented on Examples/eOverdracht-NursingHandoff-Adults.xml
> +                <reference value="Encounter/eOverdracht-encounter-01" />
Klopt, een eOverdracht encounter instance is er nog niet

2021-10-06 12:41 UTC, closed without merging